### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by pr0g** [gustavopezzi/dynamicarray#1]
Sorry I could probably make a PR for this but I thought this might be quicker as it's a very small thing I spotted 😅.

In `array.c` on line [21 and 22](https://github.com/gustavopezzi/dynamicarray/blob/c09e55ca712b7dc371e3ef3e3de0512b39649bc0/array.c#L21C8-L21C8), it looks like a rename went awry, and a variable that should be `double_curr` got renamed to `float_curr` (a find and replace mishap that's happened to us all at one time or another 😝).

https://github.com/gustavopezzi/dynamicarray/blob/c09e55ca712b7dc371e3ef3e3de0512b39649bc0/array.c#L21-L22

Also on another note, I got inspired by this (why I was looking at it in the first place) and created a fork building on this code. You can find it [here](https://github.com/pr0g/dyn-array). Feel free to take a look (it's still very WIP and will likely have bugs or be doing something wrong in places I'm sure).

Thanks!

**Comment by gustavopezzi** [comment]
Oh wow. And I even remember the `sed` command I ran on the folder that caused this issue. Thank you for the heads up. :)

**Comment by pr0g** [comment]
Not at all! 😊 Thanks for fixing! 🙂
